# Generated by Django 5.2.7 on 2025-10-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='potencia_watts',
            field=models.FloatField(default=0),
        ),
    ]
