# Generated by Django 5.2.7 on 2025-10-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_equipamento_potencia_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='vida_util_anos',
            field=models.IntegerField(default=5),
        ),
    ]
