# Generated by Django 5.2.7 on 2025-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_observacoes_equipamento_vida_util_anos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='valor_residual',
            field=models.FloatField(default=0),
        ),
    ]
