# Generated by Django 5.2.7 on 2025-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_equipamento_valor_residual'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Filamento', 'Filamento'), ('Resina', 'Resina'), ('Wash & Cure', 'Wash & Cure'), ('Outros', 'Outros')], max_length=20, null=True),
        ),
    ]
