# Generated by Django 5.2.7 on 2026-05-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_equipamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='em_manutencao',
            field=models.BooleanField(default=False),
        ),
    ]
