# Generated by Django 5.2.7 on 2026-05-14 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipamentos', '0005_equipamento_tipo'),
        ('estoque', '0008_insumos_categoria_insumos_peso_no_calculo_and_more'),
        ('precificacao', '0003_orcamento_ano_orcamento_cliente_orcamento_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.FloatField(blank=True, help_text='Obrigatório para fechar a OP. Validado na view na transição de status → concluida.', null=True, verbose_name='Quantidade utilizada (g ou ml)')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='equipamentos.equipamento', verbose_name='Impressora')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='estoque.materiaprima', verbose_name='Matéria-Prima')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('yampi', 'Yampi'), ('loja', 'Loja')], max_length=20, verbose_name='Origem')),
                ('referencia_yampi', models.CharField(blank=True, help_text='Número do pedido na Yampi (preenchido manualmente).', max_length=100, verbose_name='Referência Yampi')),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('is_enviado', models.BooleanField(default=False, help_text='Marcar apenas após confirmação de postagem. Único status manual.', verbose_name='Enviado')),
                ('data_pedido', models.DateField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('data_prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='precificacao.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido', '-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('tipo_impressao', models.CharField(choices=[('resina', 'Resina'), ('filamento', 'Filamento')], max_length=20, verbose_name='Tipo de impressão')),
                ('arquivo_stl', models.CharField(blank=True, help_text='Nome do arquivo. Ex: goblin_archer_v2.stl', max_length=255, verbose_name='Arquivo STL')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='OrdemProducaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('na_fila', 'Na fila'), ('imprimindo', 'Imprimindo'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], default='na_fila', max_length=20, verbose_name='Status')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_itens', to='pedidos.itempedido', verbose_name='Item do Pedido')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_itens', to='pedidos.ordemproducao', verbose_name='Ordem de Produção')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Produção',
                'verbose_name_plural': 'Itens da Ordem de Produção',
                'unique_together': {('ordem', 'item')},
            },
        ),
    ]
