# Generated by Django 5.2.7 on 2026-03-25 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Miniatura Guerreiro 32mm', max_length=200)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='rascunho', max_length=20)),
                ('tipo_impressao', models.CharField(blank=True, choices=[('resina', 'Resina'), ('filamento', 'Filamento')], max_length=20, null=True)),
                ('custo_impressao', models.FloatField(help_text='Custo total calculado pelo módulo de custos (R$)')),
                ('custo_modelagem', models.FloatField(default=0, help_text='Custo de modelagem 3D ou compra de arquivo STL (R$)')),
                ('outros_custos', models.FloatField(default=0, help_text='Outros custos diretos (R$)')),
                ('margem_lucro', models.FloatField(default=40.0, help_text='Margem de lucro desejada (%)')),
                ('taxa_plataforma', models.FloatField(default=2.5, help_text='Taxa da plataforma de vendas (%)')),
                ('taxa_cartao', models.FloatField(default=3.99, help_text='Taxa da administradora de cartão (%)')),
                ('custo_base', models.FloatField(default=0, help_text='Soma de todos os custos antes da margem (R$)')),
                ('preco_final', models.FloatField(default=0, help_text='Preço de venda calculado (R$)')),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
