# Generated by Django 5.2.7 on 2026-04-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente_nome',
            field=models.CharField(blank=True, help_text='Nome do cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cliente_telefone',
            field=models.CharField(blank=True, help_text='Ex: 11999999999 (só números)', max_length=20, null=True),
        ),
    ]
