# Generated by Django 5.2.7 on 2026-05-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('precificacao', '0002_orcamento_cliente_nome_orcamento_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para orçamentos sem cliente cadastrado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('numero', 'ano')},
        ),
    ]
