# Generated by Django 5.2.7 on 2026-05-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('documento', models.CharField(blank=True, help_text='Opcional — CPF (000.000.000-00) ou CNPJ (00.000.000/0000-00)', max_length=18, verbose_name='CPF / CNPJ')),
                ('tipo', models.CharField(choices=[('B2C', 'Pessoa Física'), ('B2B', 'Pessoa Jurídica / Revendedor')], default='B2C', max_length=3)),
                ('estagio', models.CharField(choices=[('lead', 'Lead'), ('primeiro', 'Primeiro Pedido'), ('recorrente', 'Recorrente'), ('inativo', 'Inativo'), ('vip', 'VIP')], default='lead', max_length=20)),
                ('origem', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('discord', 'Discord / Comunidade'), ('indicacao', 'Indicação'), ('organico', 'Busca Orgânica'), ('outro', 'Outro')], max_length=20)),
                ('canal', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('dm_insta', 'DM Instagram'), ('dm_face', 'DM Facebook'), ('email', 'Email'), ('presencial', 'Presencial')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
