# Generated by Django 5.2.7 on 2025-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('cor', models.CharField(blank=True, max_length=30, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.FloatField()),
                ('estoque_minimo', models.FloatField(default=0)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
