# Generated by Django 5.2.7 on 2025-10-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'verbose_name': 'Matéria Prima', 'verbose_name_plural': 'Matérias Primas'},
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo',
            field=models.CharField(blank=True, choices=[('filamento', 'Filamento'), ('resina', 'Resina')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='estoque.marca'),
        ),
    ]
