# Generated by Django 5.2.7 on 2025-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_marca_alter_materiaprima_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('consumivel', 'Consumível'), ('protecao', 'Proteção'), ('manutencao', 'Manutenção')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.FloatField()),
                ('estoque_minimo', models.FloatField(default=0)),
                ('preco_unitario', models.FloatField()),
                ('quantidade_minima', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
    ]
