# Generated by Django 5.2.7 on 2025-10-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='unidade',
            field=models.CharField(default='unidade', help_text='Ex: g, kg, ml, kWh', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='tipo',
            field=models.CharField(blank=True, choices=[('consumivel', 'Consumível'), ('protecao', 'Proteção'), ('manutencao', 'Manutenção'), ('energia', 'Energia'), ('outros', 'Outros')], max_length=20, null=True),
        ),
    ]
