# Generated by Django 5.2.7 on 2025-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_insumos_unidade_alter_insumos_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='preco',
        ),
        migrations.AddField(
            model_name='insumos',
            name='preco_total',
            field=models.FloatField(default=0, help_text='Preço total pago na compra (R$)'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='preco_total',
            field=models.FloatField(default=0, help_text='Preço total pago na compra (R$)'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='preco_unitario',
            field=models.FloatField(default=0, editable=False, help_text='Preço por unidade (R$/kg, R$/L, etc.)'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='unidade',
            field=models.CharField(default='kg', help_text='Ex: kg, L, g, mL', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='preco_unitario',
            field=models.FloatField(default=0, editable=False, help_text='Preço por unidade (R$/unidade, R$/kg, R$/L, etc.)'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='quantidade',
            field=models.FloatField(help_text='Quantidade total comprada (em unidades, kg, L etc.)'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='quantidade',
            field=models.FloatField(help_text='Quantidade total comprada (em kg, L etc.)'),
        ),
    ]
