# Generated by Django 5.2.7 on 2025-10-13 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_materiaprima_preco_insumos_preco_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.FloatField(help_text='Quantidade comprada (ex: 5 kg)')),
                ('preco_total', models.FloatField(help_text='Preço total da compra')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='estoque.materiaprima')),
            ],
            options={
                'verbose_name': 'Compra Matéria-prima',
                'verbose_name_plural': 'Compras Matérias-primas',
            },
        ),
    ]
