# Generated by Django 5.2.7 on 2025-10-13 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_compramateriaprima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='quantidade_minima',
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.FloatField(help_text='Quantidade comprada (ex: 5 kg, 3 L)')),
                ('preco_total', models.FloatField(help_text='Preço total da compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='estoque.insumos')),
            ],
            options={
                'verbose_name': 'Compra de Insumo',
                'verbose_name_plural': 'Compras de Insumos',
            },
        ),
    ]
