# Generated by Django 5.2.7 on 2025-10-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_insumos_quantidade_minima_comprainsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('consumivel', 'Consumível'), ('protecao', 'Proteção'), ('manutencao', 'Manutenção'), ('energia', 'Energia'), ('outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insumos',
            name='peso_no_calculo',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='tipo',
            field=models.CharField(choices=[('resina', 'Impressão com Resina'), ('filamento', 'Impressão com Filamento'), ('geral', 'Uso Geral')], max_length=20, null=True),
        ),
    ]
